#!/bin/bash

LOCDIR=`pwd`

SRCDIR="/home/frosch03/frosch03.de/www/AoE2ResSim"

#NAME=${1:0:-3}
NAME="BuildOrder"


cd $SRCDIR

ghc -o aoe2sim $NAME.hs
./aoe2sim

cd $LOCDIR

echo -e "Content-Type: text/html\n\n"
echo "<html><head><title>AoE2 Ressources Simulation</title></head><body><img src="\"../$NAME.png\"" /></body></html>"
